# Generated by Django 3.0.4 on 2020-03-28 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('W', 'waiting'), ('I', 'in_game')], default='W', max_length=1)),
                ('game', models.CharField(choices=[('CHAT', 'just_chat'), ('MIGHTY', 'Mighty'), ('NEMOS', 'Nemos')], default='CHAT', max_length=15)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
