# Generated by Django 3.0.4 on 2020-03-29 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='state',
            new_name='status',
        ),
    ]
