# Generated by Django 3.0.4 on 2020-04-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200329_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='game',
            field=models.CharField(choices=[('CHAT', 'Just Chat'), ('MIGHTY', 'Mighty'), ('NEMOS', 'Nemos')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('W', 'Waiting'), ('I', 'In Game')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
